name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    name: Drivers Packager
    runs-on: windows-latest
    strategy:
      matrix:
        device:
          - enchilada

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
      - name: Package device ${{ matrix.device }}
        shell: pwsh

        run: .\extract.ps1 ${{ matrix.device }} 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.device }}
          path: ./output/*
